---
- name: setup
  hosts: localhost

  vars_files:
    - config.yml

  tasks:
    - import_tasks: tasks/common.yml

    - import_tasks: tasks/common-desktop.yml
      when: "'gnome' in features or 'niri' in features"

    - import_tasks: tasks/desktop-gnome.yml
      when: "'gnome' in features"

    - import_tasks: tasks/app-steam.yml
      when: "'steam' in apps"

    - import_tasks: tasks/workstation.yml
      when: "'workstation' in features"